In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('spotify-2000.csv')

In [4]:
data.head()

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59

In [11]:
not_hot_songs = data[['Title', 'Artist']]

In [12]:
not_hot_songs.head()

                    Title             Artist
0                 Sunrise        Norah Jones
1             Black Night        Deep Purple
2          Clint Eastwood           Gorillaz
3           The Pretender       Foo Fighters
4  Waitin' On A Sunny Day  Bruce Springsteen

In [13]:
not_hot_songs.to_csv('not_hot.csv')

In [14]:
data = pd.read_csv('not_hot.csv')

In [16]:
data.head()

   Unnamed: 0                   Title             Artist
0           0                 Sunrise        Norah Jones
1           1             Black Night        Deep Purple
2           2          Clint Eastwood           Gorillaz
3           3           The Pretender       Foo Fighters
4           4  Waitin' On A Sunny Day  Bruce Springsteen